name: workflow to deploy an ARM Template to a resource group
on: push
  

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_RESOURCE_GROUP: "ADFGithubActions"   # set this to your Azure Resource group's name  
  AZURE_SUBSCRIPTION_ID: "d5af95fc-77ba-4fec-b542-923001f14ad6"   # set this to your Azure Subscription Id
  
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
                
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy resources
      uses: azure/data-factory-deploy-action@v1.2.0
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        # subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        dataFactoryName: "PM-ADFQA"
        armTemplateFile: "${{ github.workspace }}/PM-ADFDev/ARMTemplateForFactory.json"
        
